language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - r: 3.3
    - dist: xenial
    - os: osx
      disable_homebrew: true
      osx_image: xcode11.4
      r_check_args: ""
    - os: osx
      disable_homebrew: true
      osx_image: xcode10.1
      r_check_args: ""
#    - os: osx
#      osx_image: xcode7.3
#      r: 3.6
#      disable_homebrew: true
#      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    update: true
    packages: libgit2-dev
    sources:
      - sourceline: 'ppa:cran/libgit2'
